
version: '3.1'

vysc_project: wisdomduck
vysc_nginx:
  duck:
    listen_host: wisdomduck.sdbagel.com
    listen_path: /
    listen_port: 80
    proxy_port: 6000

services:
  duck:
    image: sdbagel/wisdomduck
    restart: always
    ports:
      - 6000:5500